---
title: "QualityControl"
author: "Systems biology group- University of Luxembourg"
date: "2023-04-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


set path


```{r}
knitr::opts_knit$set(root.dir = 'C:/Users/maria.pacheco/Documents/GitHub/basicAnalysis/')
```

load libraries
```{r}
library(readr)
library(FactoMineR)
library(factoextra)
library("biomaRt")
library(tidyverse)
library(tidyr)

```

Read data and replace NA by zeros
```{r}
knitr::opts_knit$set(root.dir = 'C:/Users/maria.pacheco/Documents/GitHub/basicAnalysis')
counts<- read_delim("C:/Users/maria.pacheco/Documents/GitHub/basicAnalysis/Data/GSE112568_count_table_CRC_C_Williams_Addendum.txt",   delim = "\t", escape_double = FALSE,     trim_ws = TRUE)
counts[is.na.data.frame(counts)]<-0

```

```{r}
  geneSymbols <-  counts$ENSEMBL_ID

human <- useMart("ensembl", dataset="hsapiens_gene_ensembl") # hgnc_symbol
  gene_coords=getBM(attributes=c("ensembl_gene_id", "start_position","end_position"), 
                    filters="ensembl_gene_id", values=geneSymbols, mart=human)
  
```
get the size from biomart
```{r}
gene_coords$size=gene_coords$end_position - gene_coords$start_position
gene_coords %>% group_by(ensembl_gene_id) %>% summarise(size= max(size)) -> gene_coords
  gene_coords <- gene_coords[gene_coords$ensembl_gene_id %in% counts$ENSEMBL_ID,]
```
Taking the maximim of count for dublicated genes
```{r}
counts_to_fpkm <- function(counts, lengths) {
  exp(log(counts) + log(1e9) - log(lengths) - log(sum(counts)) )
}
```



```{r}
counts %>% group_by(ENSEMBL_ID) %>% summarize(across(everything(), list(max)) )-> counts
df_knw_len <- counts[counts$ENSEMBL_ID %in% gene_coords$ensembl_gene_id,]
df_len <- left_join(gene_coords,df_knw_len,by=c('ensembl_gene_id'="ENSEMBL_ID"))
df_len <- df_len[!is.na(df_len$size),]


fpkm <- apply(df_len[,4:ncol(df_len)], 2, function(x) counts_to_fpkm(x, df_len$size))
fpkm <- data.frame(fpkm)
rownames(fpkm) <- df_len$ensembl_gene_id
```



log transform data and transpose data
```{r}
logdata <- t(log2(fpkm+1))
cond=c('EV', 'EV', 'EV10nME224HR_I',  'EV10nME224HR_I','1uG124hr_I', '1uG124hr_I', 'ERBtransduced','ERBtransduced')
col=cond
pal=c("EV" = "#FF007F", "EV10nME224HR_I" = "#FFAB00", "1uG124hr_I" = "blue", 
      "ERBtransduced" = "#C0CA33") 
```


Do a Principal Component Analysis 

1st and 2nd dimension
```{r}
PC <- PCA(logdata, graph = FALSE)
fviz_pca_ind(PC, col.ind=col,pointshape = 20,pointsize = 2, geom =  c("point", "text"),palette = pal)
```
1st and 3rd dimension
```{r}
PC <- PCA(logdata, graph = FALSE)
#x11()
name=paste("Output/Pca_D1-D3",".png", sep="")
#png(name, width=1000, height=400)
fviz_pca_ind(PC, col.ind=col,pointshape = 20,pointsize = 2, geom =  c("point", "text"),palette = pal,axes=c(1,3))
#dev.off()

```
boxplot
```{r}
x=1:dim(logdata)[1]
x
boxplot(logdata~x,
main = "Data distribution",
names = col,
col = c("gray"),
border = "brown",
horizontal = FALSE,
notch = TRUE
)

```
Density plot
```{r}
color= 1:length(col)
d <- density(logdata[1,])
plot(d,main="density", ylab="Density", xlim=c(0,4))
for (s in 2:length(cond)){
  d <- density(logdata[s,])
  lines(d,col=color[s],xlim=c(0,2))
}
```
Print fpkm
```{r}
name=paste(getwd(),"/Quality Control/Output/fpkm.txt",sep="")
name=gsub("/", "//", name)
write.table(fpkm, name, append = FALSE)
```
 
