function[results] = hint(num)

H = {'You can either use a function or open the model variable.',...
    'Have a look at the size function.',...
    'Have a look at the unique function.',...
    'You can look up the answer in the table or use the ismember function together with the sum function.',...
    'no hint available for this question',... %5
    'Use indices.',...
    'We have used these functions before.',...
    'Feel free to use google :)',...
    'Feel free to use google :)',...
    'Feel free to use google :)',... %10
    'Have a look at the text in the script again',...
    'You can use the setdiff function to find differences. Use the indices of the consitent reactions in vector A.',...
    'Have a look at the sum function ',...
    'no hint available for this question',... %14
    'You want to find the difference between the model reactions and the reaction that can carry a flux. Try setdiff',...
    'Make sure you understand why we constrain this bound and not the other',... %16
    'We have previously build a model from the vector A, have a look.',... %17
    'Feel free to use google :)',...
    'Feel free to use google :)',...
    'We have previously build a model from the vector A, have a look.',... %20
    'Have a look as ismember',...
    'No hint available for this question',... %22
    'Let us know if there is an issue',...
    'Have a look at sum',...
    'Have a look at sum',...
    'Have a look at sum',...
    'Have a look at sum',...
    };

h = H(num);
disp(strcat('Hint for question',{' '}, num2str(num),':' ,{' '} ,h))
end