function[answer] = Ques(num, varargin, varargin2)

if(nargin) >1
    
    answer = varargin;
    Question = num;
    if nargin>2
    submission(answer, Question, varargin,varargin2 )
    else
        save
            submission(answer, Question, varargin);
    end
    
else
   
    Q = {'How many fields are in the model structure array?\n',... %1
        'How many genes are in the model?\n',...%2
        'How many unique pathways are in the model?\n', ...
        'How many reactions are in the subSystems that are "Transport, extracellular?"\n',...
        'Find the names of the extracellular transporters\n',...
        'What is the 59th metabolite?\n',...%6
        'How many reactions take place in the cytoplasm?\n',...
        'In a GPR expression with a BOOLEAN OR, if one of the genes is active and the other is inactive, is the reaction active? (Yes/No)\n',...
        'In a GPR expression with a BOOLEAN AND, if one of the genes is active and the other is inactive, is the reaction active? (Yes/No)\n', ...
        'If Gene 4 is expressed and the others are not, is the reaction active?\n',...
        'How do you call a model in which all the reactions are connected directly or indirectly to the environment? \n',...
        'One reaction is blocked. What is the name (model.rxns) of this reaction?\n',...
        'How many exchange reactions are in the model?\n',...
        'How many metabolites are present in the medium?\n',...
        'Compute Ex_to_close\n', ...
        'Do you have to constraint the upper or lower bounds? Type ub for upper and lb for lower\n',...
        'What is the size of the medium_constraint_model (number of reactions)?\n',...
        'What will be the expression associated to the reaction\n', ...
        'What will be the score associated to the reaction\n', ...
        'What is the size of the breast cancer model?\n',... %20
        'What is the in the index of the biomass_reaction?\n',...       
        'For which cells is the optimization of the biomass production reasonable? (a, b, c, d, e, f, g,h)\n',...
        'What is this maximal growth rate for the consistent model?\n',... %23
        'You need to replace the xxxx with which output?\n',...
        'Which genes completely reduce the flux through the biomass reaction to 0 in the breast cancer model?\n',...
        'For a threshold of 0.5, how many genes are essential in the consistent model?\n',...
        'For a threshold of 0.5, which genes are essential in the breast cancer model?\n',...
        };
    name = strcat('answer', num2str(num), '.mat' );
        name2 = strcat('answer', num2str(num-1), '.mat' );
       
if isfile(['SavedAnswers/', name2])|| num==1
    
    if isfile(['SavedAnswers/', name])
        load (['SavedAnswers/', name])
        disp('correct')
        
    else
        prompt = (Q{num});
        
        answer = input(prompt,'s');
        Question = num;
        submission(answer, Question);
        
        return
    end
else
    return
end
end
